import '@/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


import { Montserrat } from "next/font/google";
import Header from './Header';

const montserrat = Montserrat({subsets: ['cyrillic']})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
